name: Deploy Vision inmobiliaria backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js v ${{ matrix.node-version}} and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          registry-url: 'https://registry.yarnpkg.com/'

      - name: Print Node.js version
        run: node --version

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH Connection and Commands
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" 'cd .. && cd home && cd vision-inmobiliaria-nest && node --version &&  yarn deploy'
